#postgress
spring.datasource.url=jdbc:postgresql://dpg-d97np4eq1p3s73f5htr0-a.singapore-postgres.render.com/moneymanager_cyrn_user
spring.datasource.username=moneymanager_cyrn_user
spring.datasource.password=h0MeWibjuyRfdO8FOK6uRHs53QOMVacJ
